on:
  push:
    paths:
      - src/main.py
  schedule:
    - cron: '0 0 * * *'
name: Test
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
    - name: Run tests
      env:
        DATABASE_URL: ${{ vars.DATABASE_URL }}
        LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        poetry run pytest tests/test_scraper.py
